/** A user authenticated via GitHub OAuth, mirrored in the `users` table. */
export interface User {
  id: string;
  github_id: number;
  github_username: string;
  github_access_token: string;
  avatar_url: string | null;
  created_at: string;
}

/** A repository that has been connected to AI Code Reviewer. */
export interface Installation {
  id: string;
  user_id: string;
  repo_full_name: string;
  repo_id: number;
  github_installation_id: number | null;
  enabled: boolean;
  created_at: string;
}

export type PullRequestStatus = "pending" | "reviewing" | "completed" | "failed";

/** A pull request that has been (or is being) reviewed. */
export interface PullRequest {
  id: string;
  installation_id: string;
  github_pr_number: number;
  title: string;
  author: string;
  head_sha: string;
  status: PullRequestStatus;
  overall_score: number | null;
  security_score: number | null;
  performance_score: number | null;
  readability_score: number | null;
  correctness_score: number | null;
  pr_url: string;
  created_at: string;
  reviewed_at: string | null;
}

export type Severity = "critical" | "warning" | "suggestion";
export type Category = "security" | "performance" | "readability" | "correctness" | "testing";

/** A single review comment generated by the AI reviewer. */
export interface ReviewComment {
  id: string;
  pull_request_id: string;
  filename: string;
  line_number: number | null;
  severity: Severity;
  category: Category;
  comment: string;
  suggestion: string | null;
  created_at: string;
}

/** Shape returned by the Anthropic model for a single diff chunk review. */
export interface AIReviewResult {
  comments: {
    line: number;
    severity: Severity;
    category: Category;
    comment: string;
    suggestion?: string;
  }[];
  fileScore: number;
}

/** Minimal GitHub repo shape used by the dashboard "add repository" flow. */
export interface GitHubRepo {
  id: number;
  full_name: string;
  private: boolean;
  html_url: string;
}

/** Event payload sent to Inngest when a PR is opened/updated. */
export interface GithubPrOpenedEvent {
  name: "github/pr.opened";
  data: {
    installationId: string;
    repoFullName: string;
    githubPrNumber: number;
    headSha: string;
    prUrl: string;
    title: string;
    author: string;
    pullRequestId: string;
  };
}
